"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 環境変数の読み込み
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])


# Application definition

# admin は入れていない（#32 で削除した）。公開 URL にログイン口を作らないため。
# 費用と実行件数をブラウザから見るために戻す余地は残してあり（#39）、そのときに必要な
# auth / contenttypes と、下の AuthenticationMiddleware・auth context processor は
# そのままにしている。admin が無いので使われていないように見えるが、消さないこと。
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.judge",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# セキュリティ
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # テスト（CI）は DEBUG=False で走るが、テストクライアントのリクエストは
    # 平文のため、有効のままだと全部 301 になる。そこだけ False にできるよう
    # 環境変数で受ける。本番でリダイレクトがループしたときに、リビジョンの
    # 環境変数だけで戻せる利点もある。
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 300


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 本番（DEBUG=False）では DATABASE_URL の明示を必須にし、未設定なら起動させない。
# 永続ディスクの無い環境（Cloud Run など）では、フォールバック先の SQLite にも
# 例外を出さずに書けてしまう。その状態で動くと DailyUsage がインスタンスごと
# （かつ再起動ごと）に分かれ、SITE_DAILY_LIMIT の歯止めが静かに外れるため、
# 設定漏れは起動時に止める。
#
# 止めるのは「未設定」だけで、エンジンの種類は見ない。永続ディスクを持つ環境
# （Fly.io のボリュームなど）で SQLite を選ぶ構成は、パスを明示すれば通る。
# 意図した選択は妨げず、書き忘れだけを塞ぐ。
#
# system check ではなくここで落とすのは、gunicorn が system check を走らせない
# ため。settings で落とせばワーカーが起動せず、壊れた設定がトラフィックを
# 受け取らない（Cloud Run なら新しいリビジョンが ready にならない）。
if not DEBUG and not env.str("DATABASE_URL", default=""):
    raise ImproperlyConfigured(
        "DEBUG=False では DATABASE_URL の設定が必須です。"
        "マネージドな PostgreSQL の接続文字列か、永続ディスク上の SQLite の"
        "パス（例: sqlite:////data/db.sqlite3）を指定してください。"
        "開発用 SQLite への暗黙のフォールバックは、SITE_DAILY_LIMIT の"
        "歯止めが静かに外れるため本番では行いません。"
    )

# CONN_MAX_AGE は既定（0：リクエストごとに接続）のままにしている。サーバーレス
# Postgres（Neon など）は数分で自動サスペンドするため接続を使い回しても切れて
# いる可能性があり、かつ1リクエストあたりの DB 操作は DailyUsage の1行だけで、
# 判定そのものにかかる時間（数秒〜）に比べれば接続の往復は無視できるため。
DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}

# アップロードファイルの取り扱い
# 既定の FILE_UPLOAD_HANDLERS は 2.5MB を超えるリクエストを
# TemporaryFileUploadHandler で OS の一時ディレクトリに書き出す。
# 「入力内容をサーバー側に保存しない」という約束をディスク経由で崩さないため、
# ハンドラをメモリのみに固定する。
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
]
# forms.MAX_IMAGE_SIZE（5MB）超の画像は form 側で拒否するが、その判定は
# multipart のパース後に行われる。ここを form の上限より大きく取ることで、
# 拒否対象のファイルもメモリ上で受け切り、正しいエラーメッセージを返せる。
# （大小関係は apps/judge/tests/test_no_stored_input.py で検証している）
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024  # 6MB

# LOGGING関係
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            # ログの出力形式（時刻、ログレベル、モジュール名、メッセージ）
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
        },
        "usage": {
            # 使用量のログは、時刻をメッセージ側に持たせる。standard は秒まで
            # 出るため、ここでは付けない（判定した時刻から利用者をたどれる余地を
            # 残さないよう、時単位に丸めた値だけにする）。
            "format": "%(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        # トークン使用量は費用の把握に使うため、集計しやすいよう標準出力へ
        # 分けて出す（引数なしの StreamHandler は標準エラーになる）。
        "usage_stdout": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "usage",
        },
        # 必要に応じてファイル出力などもここに追加
    },
    "loggers": {
        # ここがポイント！ アプリ名を指定して共通ロガーを作成
        "apps.judge": {
            "handlers": ["console"],
            "level": "DEBUG",  # 開発時はDEBUGなどに変更
            "propagate": False,
        },
        # トークン使用量。DB には保存せず、標準出力に1行ずつ出すだけにする。
        # 親（apps.judge）へは流さない（標準エラーに二重に出さないため）。
        "apps.judge.usage": {
            "handlers": ["usage_stdout"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ja-jp"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

MESSAGE_TAGS = {
    messages.ERROR: "danger",  # error を danger にマッピング
}

VIEW_TEST_MODE = env.bool("VIEW_TEST_MODE", default=False)

CLAUDE_MODEL = env("CLAUDE_MODEL", default="claude-sonnet-5")

# 1人あたり1日に判定できる件数。連打への摩擦で、ブラウザの Cookie で数える。
# Cookie を消せば戻るため、費用の歯止めは下の SITE_DAILY_LIMIT 側に置いている。
PERSON_DAILY_LIMIT = env.int("PERSON_DAILY_LIMIT", default=4)

# サイト全体で1日に判定できる件数。月額の利用上限を1日で使い切られると
# 翌月まで全員が判定を受けられなくなるため、被害をその日のうちに閉じ込める。
#
# 1件あたりの費用は、判定プロンプト（約6,300トークン）がプロンプトキャッシュに
# 当たるかどうかで2倍以上変わる。散発的に使われると毎回キャッシュを書き直すため、
# 実測は $0.019（連続実行・ほぼ全部命中）〜 $0.041（毎回ミス）の幅がある。
# 11件/日は、毎回ミスする最悪の想定でも 31日で約 $14 に収まる値。
# 上限を変えるときは、この関係と契約している月額上限を必ず見直すこと。
#
# 実際のキャッシュ命中率は token_usage ログ（cache_read と cache_write）で
# 測れる。運用して実測が取れたら、この値を見直す。
SITE_DAILY_LIMIT = env.int("SITE_DAILY_LIMIT", default=11)

# anthropic SDK の更新を検証するときだけ True にする（実 API を叩くため費用が出る）。
# 引数の生存確認（AnthropicSDKSignatureTests）は常時実行で、ここには依存しない。
ANTHROPIC_SDK_TEST = env.bool("ANTHROPIC_SDK_TEST", default=False)
ANTHROPIC_SDK_TEST_MODEL = env("ANTHROPIC_SDK_TEST_MODEL", default="claude-haiku-4-5")
