# Generated by Django 6.0.7 on 2026-07-21 13:18

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('encrypted_config', encrypted_model_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
