# Generated by Django 6.0.7 on 2026-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付（JST）')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='判定件数')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
